### ISSUE TITLE
Zone accessories state does not update

### ISSUE THREAD

**Issue by dgburtonbv** [dustindclark/homebridge-envisalink#4]
Zone accessories' state doesn't seem to update - for example a "door" zone's state doesn't update in Homekit, same with the motion zone type.

I can see that the Envisalink is receiving the notification from the DSC panel ok, it's just the Homekit accessory's state doesn't update:

Here's a cut from the log of a person walking infront of a motion sensor:

Zone 007 is open
Partition 1 is Ready and Force Arming is Enabled
[7/20/2016, 8:15:37 PM] Partition status changed to: { partition: 1, code: '653' }
Set status on accessory Alarm to {"name":"Partition Ready - Force Arming Enabled","pre":"Partition","bytes":1,"post":"is Ready and Force Arming is Enabled","send":"readyforce","action":"updatepartition"}
Zone 007 is restored
Partition 1 Ready
[7/20/2016, 8:15:42 PM] Partition status changed to: { partition: 1, code: '650' }
Set status on accessory Alarm to {"name":"Partition Ready","pre":"Partition","bytes":1,"post":"Ready","send":"ready","action":"updatepartition"}

**Comment by aaronjedwards** [comment]
I have noticed the same issue. I am using iOS 10 and the Home app and the zone status only updates when I close and open the app. I have tried creating automations to trigger other accessories when motion is detected, but this only seems to work if the motion sensor is currently "open" at the time I open the app.

**Comment by skcuslleb** [comment]
Have you updated index.js? The last checkin says:

> Update index.js
> - Add instantaneous update to the homekit app of the zone status and the partition status
> - Corrected ContactPosition 
> - Added Obstuction service to detect if system is ready

It hasn't been pushed to npm yet, so you'll just have to patch it manually.

**Comment by dustindclark** [comment]
@aaronjedwards / @afrustagli / @dgburton, can you confirm that this is fixed with 0.1.4?  Thanks.

**Comment by ghost** [comment]
Hi guys
I had a question. Is there a way to get zone status updates without the need to put your pin in the config. I don't care to arm/disarm via homebridge, rather id rather get notified when a door/window opens and closes and build robots off of that

**Comment by ghost** [comment]
so i can confirm that the update status issue, is still an issue. It reads all zones and the alarm but it consistently just says updating all the time. Eventually it just says no response...is there a fix for this yet?

**Comment by ghost** [comment]
Um anyone able to fix this one?

**Comment by ToddGreenfield** [comment]
@sats4eva as mentioned above be sure you have the latest version. Does this happen with **all** zones? What about doors/windows which you can leave open for example while testing? My alarm's motion sensors switch on/off quickly so you need to catch them in action, and also the motion sensors might not re-trip with in a certain time period. So you can be standing in front of them and they may not show up as showing motion, but they are working and communicating to the alarm panel.  Do you have an app like all-secure that you can use to test the alarm/envisalink status?

**Comment by ghost** [comment]
Hello
It happens with all sensors. The issue isn't even whether I can test the status. It just continually says updating in the home app for all sensors (motion, door and window). I've tried other apps as well and they don't seem to respond. I did download the latest version. Just to make sure what command do you use to install? I read somewhere it's not uploaded to npm yet?

Sent from my iPhone

On Feb 27, 2017, at 7:53 AM, Todd Greenfield <notifications@github.com<mailto:notifications@github.com>> wrote:


@sats4eva<https://github.com/sats4eva> as mentioned above be sure you have the latest version. Does this happen with all zones? What about doors/windows which you can leave open for example while testing? My alarm's motion sensors switch on/off quickly so you need to catch them in action, and also the motion sensors might not re-trip with in a certain time period. So you can be standing in front of them and they may not show up as showing motion, but they are working and communicating to the alarm panel. Do you have an app like all-secure that you can use to test the alarm/envisalink status?

**Comment by ToddGreenfield** [comment]
Ah, gotcha. I think the alarm might only be able to bind to one system at a time. Are you connecting any other hub/app/system to the envisalink device (like a Smartthings maybe)? Are you able to run homebridge successfully without this plugin for envisalink? What is in your config.json? What does the logfile say after you start homebridge?

to install - use "npm install -g homebridge-envisalink" (without quotes, and you may need to run with sudo) "sudo npm install -g homebridge-envisalink".

Also, the latest version from the recent pulls (updates) doesnt appear to be pushed to NPM, so you would need to download the version of index.js here on github and overwrite your local version in your {.npm-global}/lib/node_modules/homebridge-envisalink (wherever your npm-global location is).

**Comment by ghost** [comment]
Hi no I've only got it connected to EnvisaLink to homebridge no other hubs

So I downloaded it as you said and over wrote by the latest index.js as you mentioned. There is some slight progress. Before everything used to say updating. Now it sees the sensors connected to my EnvisaLink and says updating only for those sensors. Anything else connected to my other hubs (lights, doors, garage openers etc) are now showing a status. However all my DSC sensors still show updating and eventually go to no response. Any other thoughts?

Sent from my iPhone

On Feb 27, 2017, at 6:05 PM, Todd Greenfield <notifications@github.com<mailto:notifications@github.com>> wrote:


Ah, gotcha. I think the alarm might only be able to bind to one system at a time. Are you connecting any other hub/app/system to the envisalink device (like a Smartthings maybe)? Are you able to run homebridge successfully without this plugin for envisalink? What is in your config.json? What does the logfile say after you start homebridge?

to install - use "npm install -g homebridge-envisalink" (without quotes, and you may need to run with sudo) "sudo npm install -g homebridge-envisalink".

Also, the latest version from the recent pulls (updates) doesnt appear to be pushed to NPM, so you would need to download the version of index.js here on github and overwrite your local version in your {.npm-global}/lib/node_modules/homebridge-envisalink (wherever your npm-global location is).

**Comment by ToddGreenfield** [comment]
Can  you log into your envisalink via the url and see network status? When you login, click the Network link on the upper right corner. Then, what does your TPI Status show at the bottom? Should should your homebridge server IP and say Online.

Can you paste your config.json or the part that has the envisalink portion?

**Comment by ghost** [comment]
Hi there. So here was my mistake. In my password field I was using my web password not local password (doh). It seems to be working now. And now the tpi status shows online. Thanks so much

So another question both my EnvisaLink and homebridge randomly change ip addresse. Is there a way to make the ip static for the EnvisaLink? I read somewhere not to do that

Sent from my iPhone

On Feb 27, 2017, at 7:26 PM, Todd Greenfield <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you log into your envisalink via the url and see network status? When you login, click the Network link on the upper right corner. Then, what does your TPI Status show at the bottom? Should should your homebridge server IP and say Online.

Can you paste your config.json or the part that has the envisalink portion?

**Comment by ghost** [comment]
Alright so it worked for a bit and then back to its crazy updating state...it updated ALL my accessories and platforms now and it can take unto 5-6 min for it to all come back...here my my config.json envisalink piece


{
			"platform": "Envisalink",
			"host": "192.168.1.34",
			"deviceType": "DSC",
			"password": “6 digit password”,
			"pin": "0000",
			"suppressZoneAccessories": false,
			"partitions": [{
				"name": "alarm"
			}],
			"zones": [{
				"name": "Front Door",
				"type": "door",
				"partition": 1
			}, {
				"name": "Hall motion",
				"type": "motion",
				"partition": 1
			}, {
				"name": "Family Room Motion",
				"type": "motion",
				"partition": 1
			}, {
				"name": "BSMT Motion",
				"type": "motion",
				"partition": 1
			}, {
				"name": "Garage",
				"type": "door",
				"partition": 1
			}, {
				"name": "Kitchen Window and Sliding Door",
				"type": "door",
				"partition": 1
			}, {
				"name": "Family Room Windows",
				"type": "window",
				"partition": 1
			}, {
				"name": "Basement Door",
				"type": "door",
				"partition": 1
			}]
		}

**Comment by dustindclark** [comment]
@sats4eva, you'll need to configure your router to reserve a local IP for your envisalink device.  The steps for this are specific to your router (search your router docs for DHCP Reservation).  You may have IP conflict issues if you attempted to configure a static IP using an address that can be DHCP-assigned to another device.

**Comment by ghost** [comment]
@dustindclark thanks I've gone ahead and done that. Still having some issues though with the update times...i mean its working but after i trigger something with the alarm, it renders all my other accessories as "updating" for about 3-4 min before i can use them again. wonder why? do you guys see anything wrong with my config file above?

**Comment by ToddGreenfield** [comment]
@sats4eva I was doing to merging/testing on this plugin and just noticed that there is a serious lag/delay when NOT using a homekit hub (iPad or ATV). When I use the hub (old iPad in my case), the response time is almost instant with this plugin/envisalink. When I am testing without a homekit hub (just an iPhone), delays.

**Comment by dustindclark** [comment]
Closing out old issue.  Please re-open if this issue persists on the latest version.
